#!/usr/bin/env python3
import os
import sys

def text_to_cpp_string(text):
    """Convert text to C++ raw string literal"""
    # Escape backslashes and quotes
    escaped = text.replace('\\', '\\\\').replace('"', '\\"')
    return escaped

def generate_header(input_file, output_file, var_name):
    """Convert JS file to C++ header"""
    
    print(f"📄 Processing: {input_file}")
    
    if not os.path.exists(input_file):
        print(f"❌ File not found: {input_file}")
        return False
    
    # Read JS file
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Convert to C++ string (no encryption for now - simple version)
    cpp_content = text_to_cpp_string(content)
    
    # Generate C++ header
    header = f'''// Auto-generated from {os.path.basename(input_file)}
// DO NOT EDIT THIS FILE MANUALLY

#ifndef YTPRO_{var_name.upper()}_H
#define YTPRO_{var_name.upper()}_H

namespace ytpro {{

// Original size: {len(content)} bytes
const char* {var_name}_data = 
R"YTPRO_DELIMITER({content})YTPRO_DELIMITER";

}} // namespace ytpro

#endif // YTPRO_{var_name.upper()}_H
'''
    
    # Create output directory if needed
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    # Save header
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(header)
    
    print(f"✅ Generated: {output_file}")
    print(f"   Size: {len(content)} bytes\n")
    return True

def main():
    print("🚀 YTPro - JS to C++ Header Converter\n")
    
    # File mappings
    files = [
        ('app/src/main/assets/script.js', 'app/src/main/cpp/scripts/script.h', 'script'),
        ('app/src/main/assets/bgplay.js', 'app/src/main/cpp/scripts/bgplay.h', 'bgplay'),
        ('app/src/main/assets/innertube.js', 'app/src/main/cpp/scripts/innertube.h', 'innertube'),
    ]
    
    success_count = 0
    for input_file, output_file, var_name in files:
        if generate_header(input_file, output_file, var_name):
            success_count += 1
    
    print(f"\n{'='*50}")
    print(f"✅ Converted {success_count}/{len(files)} files successfully!")
    print(f"{'='*50}\n")
    
    if success_count == len(files):
        print("📋 Next steps:")
        print("   1. Build your project: ./gradlew assembleRelease")
        print("   2. Scripts will be embedded in libyggtpro-native.so")
        return 0
    else:
        print("⚠️ Some files failed to convert!")
        return 1

if __name__ == '__main__':
    sys.exit(main())
